// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5SS8usCOsML1hxnkO9lT9flaFl88xEPk',
    appId: '1:658574511312:web:a8f6d14babe2ecaff0e2d5',
    messagingSenderId: '658574511312',
    projectId: 'maxrun-photoapp',
    authDomain: 'maxrun-photoapp.firebaseapp.com',
    storageBucket: 'maxrun-photoapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvI7HiGs2Gas2duZYOtgbX21E9UA2-pF4',
    appId: '1:658574511312:android:47dd84bbb5b467d8f0e2d5',
    messagingSenderId: '658574511312',
    projectId: 'maxrun-photoapp',
    storageBucket: 'maxrun-photoapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIhGNcdqcQ6pD88ckpSi3i8Uz3VvgHNcM',
    appId: '1:658574511312:ios:c35035c0fbf05f96f0e2d5',
    messagingSenderId: '658574511312',
    projectId: 'maxrun-photoapp',
    storageBucket: 'maxrun-photoapp.appspot.com',
    iosBundleId: 'kr.co.maxrun.photoapp.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIhGNcdqcQ6pD88ckpSi3i8Uz3VvgHNcM',
    appId: '1:658574511312:ios:b73ca8b7c887d10ef0e2d5',
    messagingSenderId: '658574511312',
    projectId: 'maxrun-photoapp',
    storageBucket: 'maxrun-photoapp.appspot.com',
    iosBundleId: 'kr.co.maxrun.photoapp.RunnerTests',
  );
}
